spring.application.name=OWL App
# Server Configuration
server.servlet.context-path=/owl

spring.jpa.hibernate.ddl-auto=none

# SQL 和參數綁定日誌配置
spring.jpa.show-sql=false
#這樣可以關閉 OSIV (Open Session in View)，避免在視圖渲染期間執行數據庫查詢。
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.descriptor.sql=trace
spring.jpa.properties.hibernate.use_sql_comments=true

# Show binding parameter values
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE
# 启用 LDAP 和 Security 相关日志
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.ldap=DEBUG
logging.level.org.springframework.security.ldap=TRACE

# Oracle Database, Tiptop
spring.datasource.oracle.url=jdbc:oracle:thin:@192.168.10.21:1521:topprod
#正式區username=tw, 測試區username=tw_test_01
spring.datasource.oracle.username=tw
#spring.datasource.oracle.username=tw_test_01
spring.datasource.oracle.password=tw
#spring.datasource.oracle.driver-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver


# MicrosoftSQL Database, HRM
#spring.jpa.mssql.hibernate.ddl-auto=none
spring.datasource.mssql.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.mssql.url=jdbc:sqlserver://192.168.10.23:1433;DatabaseName=HRMDB;encrypt=false;trustServerCertificate=false
spring.datasource.mssql.url=jdbc:sqlserver://192.168.10.23:1433;DatabaseName=HRMDB;encrypt=true;trustServerCertificate=true;enabledTLSProtocols=TLSv1
#jdbc.mssql.easyflow.url=jdbc:sqlserver://192.168.10.23:1433;DatabaseName=EFNETDB
spring.datasource.mssql.username=sa
spring.datasource.mssql.password=dsc@12345

# 本地数据库配置（用于OWL项目自身的数据）
spring.datasource.url=jdbc:h2:mem:owldb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# OWL 配置
owl.ontology.base-path=./ontologies
# 设置 OWL 导出路径
tiptop.owl.export.path=./owl-exports

# 允許Rest的 origins
cors.allowed-origins=http://localhost:5173,http://localhost:5175,http://192.168.20.81:5173,http://192.168.20.81:5175,http://192.168.1.105:5175,http://192.168.40.169:5175
